# Generated by Django 3.0.1 on 2019-12-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=10)),
                ('low_size', models.FloatField()),
                ('high_size', models.FloatField()),
                ('color', models.CharField(max_length=1)),
                ('clarity', models.CharField(max_length=4)),
                ('caratPrice', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
